apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: default
spec:
  # We explicitly turn off security to stop the crashes
  mtls:
    enabled: false
  # Enable observing traces (optional but good)
  tracing:
    samplingRate: "1"