backend:
  image: hackathon-backend:latest
  pullPolicy: Never   # <--- FIX 1: Forces K8s to use your local image
  replicas: 1
  service:
    type: ClusterIP
    port: 8000

frontend:
  image: hackathon-frontend:latest
  pullPolicy: Never   # <--- FIX 1: Forces K8s to use your local image
  replicas: 1
  service:
    type: NodePort
    port: 3000

secrets:
  # Values will be injected from environment or set manually during install
  # helm install ... --set secrets.databaseUrl=... --set secrets.openaiApiKey=...
  databaseUrl: "postgresql://neondb_owner:npg_zJWhtTuCL67g@ep-silent-wave-adpc6smg-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"
  openrouterApiKey: "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"
