apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notification
  labels:
    app: notification-service
spec:
  replicas: {{ .Values.notificationService.replicas }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "notification-service"
        dapr.io/app-port: "8001"
    spec:
      containers:
      - name: notification-service
        image: "{{ .Values.notificationService.image.repository }}:{{ .Values.notificationService.image.tag | default .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.notificationService.image.pullPolicy }}
        ports:
        - containerPort: 8001
