apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-recurring
  labels:
    app: recurring-service
spec:
  type: {{ .Values.recurringService.service.type }}
  ports:
    - port: {{ .Values.recurringService.service.port }}
      targetPort: 8002
      protocol: TCP
  selector:
    app: recurring-service
